//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Common
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Common()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", typeof(Common).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Your account is activated now!.
		/// </summary>
		public static string AccountActivated
		{
			get
			{
				return ResourceManager.GetString("AccountActivated", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Account created successfully!.
		/// </summary>
		public static string AccountCreated
		{
			get
			{
				return ResourceManager.GetString("AccountCreated", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Actively activation link.
		/// </summary>
		public static string ActivelyActivationLink
		{
			get
			{
				return ResourceManager.GetString("ActivelyActivationLink", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to To activate your account click the link: .
		/// </summary>
		public static string ActivelyClickActivationLink
		{
			get
			{
				return ResourceManager.GetString("ActivelyClickActivationLink", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Actively password recovery.
		/// </summary>
		public static string ActivelyPasswordRecovery
		{
			get
			{
				return ResourceManager.GetString("ActivelyPasswordRecovery", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to To reset your password click here: .
		/// </summary>
		public static string ActivelyPasswordRecoveryLink
		{
			get
			{
				return ResourceManager.GetString("ActivelyPasswordRecoveryLink", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Avatar has been set successfully!.
		/// </summary>
		public static string AvatarChanged
		{
			get
			{
				return ResourceManager.GetString("AvatarChanged", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Verification email sent successfully!.
		/// </summary>
		public static string EmailVerificationSentSucces
		{
			get
			{
				return ResourceManager.GetString("EmailVerificationSentSucces", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Error!.
		/// </summary>
		public static string Error
		{
			get
			{
				return ResourceManager.GetString("Error", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid code.
		/// </summary>
		public static string InvalidCode
		{
			get
			{
				return ResourceManager.GetString("InvalidCode", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid user name.
		/// </summary>
		public static string InvalidUserName
		{
			get
			{
				return ResourceManager.GetString("InvalidUserName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Login.
		/// </summary>
		public static string Login
		{
			get
			{
				return ResourceManager.GetString("Login", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Login failed. Invalid user name or password or account is not activated..
		/// </summary>
		public static string LoginFailed
		{
			get
			{
				return ResourceManager.GetString("LoginFailed", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Password has been changed successfully!.
		/// </summary>
		public static string PasswordChangedSuccessfully
		{
			get
			{
				return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Password and confirmation password do not match!.
		/// </summary>
		public static string PasswordNotMatch
		{
			get
			{
				return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to A link with the option to change the password has been sent to the e-mail address provided, open it and follow the instructions: .
		/// </summary>
		public static string PasswordResetRequest
		{
			get
			{
				return ResourceManager.GetString("PasswordResetRequest", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Privacy law default.
		/// </summary>
		public static string Privacy
		{
			get
			{
				return ResourceManager.GetString("Privacy", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Register.
		/// </summary>
		public static string Register
		{
			get
			{
				return ResourceManager.GetString("Register", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ups! Something went wrong!.
		/// </summary>
		public static string SomethingWentWrong
		{
			get
			{
				return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Success!.
		/// </summary>
		public static string Success
		{
			get
			{
				return ResourceManager.GetString("Success", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Two-factor email authorization is set off!.
		/// </summary>
		public static string TwoFactorAuthIsOff
		{
			get
			{
				return ResourceManager.GetString("TwoFactorAuthIsOff", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Two-factor email authorization is set now!.
		/// </summary>
		public static string TwoFactorAuthIsSet
		{
			get
			{
				return ResourceManager.GetString("TwoFactorAuthIsSet", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User does not exist!.
		/// </summary>
		public static string UserDoesNotExist
		{
			get
			{
				return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User already exist!.
		/// </summary>
		public static string UserExist
		{
			get
			{
				return ResourceManager.GetString("UserExist", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Welcome on Actively!.
		/// </summary>
		public static string Welcome
		{
			get
			{
				return ResourceManager.GetString("Welcome", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Welcome!.
		/// </summary>
		public static string Welcome1
		{
			get
			{
				return ResourceManager.GetString("Welcome1", resourceCulture);
			}
		}
	}
}
